-- 2.1 Salesperson performance summary --

SELECT 
    "Sales Person",
    SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS completed_shipments,
    SUM(CASE WHEN Status = 'Active' THEN 1 ELSE 0 END) AS active_shipments,
    SUM(CASE WHEN Status = 'Returned' THEN 1 ELSE 0 END) AS returned_shipments
FROM Shipment
GROUP BY "Sales Person"
ORDER BY completed_shipments DESC;

-- 2.2 Revenue generated by month --

SELECT 
    DATE_TRUNC('month', Date) AS revenue_month,
    SUM(Sales) AS total_revenue
FROM Shipment
WHERE Status = 'Completed'
GROUP BY revenue_month
ORDER BY revenue_month;

-- 2.3 Top product categories by revenue --

SELECT 
    p.Category,
    SUM(s.Sales) AS total_revenue
FROM Shipment s
JOIN Product p ON s.Product = p.Product
WHERE s.Status = 'Completed'
GROUP BY p.Category
ORDER BY total_revenue DESC;

-- 2.4 Salesperson contribution to revenue --

SELECT 
    "Sales Person",
    SUM(Sales) AS total_revenue
FROM Shipment
WHERE Status = 'Completed'
GROUP BY "Sales Person"
ORDER BY total_revenue DESC;